### PR TITLE
Snapshot-test extendr macros expansions

### PR DESCRIPTION
**Pull request by Ilia-Kosenkov**
- Test generated code
- Visualize expansion for reference

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
Blocked by https://github.com/dtolnay/install/issues/12. If it will not be resolved by the author/us, I will switch to just `cargo install` cmd.

**Comment by Ilia-Kosenkov** [comment]
Dayum, snapshot tests are disabled by default on CRAN so they were not executed here >_<. I was debugging unreachable code on CI

**Review by CGMossa — APPROVED** [review]
Honestly, I don't know this stuff anyways, but nothing came up when looking through it...

I find the `nzchar` function odd. It just returns `TRUE/FALSE`, but that's not what the `?nzchar` says about it...

LGTM

**Comment by Ilia-Kosenkov** [comment]
Wait, what's wrong with `nzchar`? I did not get it

**Comment by CGMossa** [comment]
>nchar takes a character vector as an argument and returns a vector whose elements contain the sizes of the corresponding elements of x.
but it returns boolean/logical.

**Comment by Ilia-Kosenkov** [comment]
Ah, but there are two functions. `nchar` counts characters, and `nzchar` (I read it as non-zero characters) just tells us if string is not empty.

**Pull request merged**
