### PR TITLE
Generate ndarray-related documentations

### PR DESCRIPTION
**Pull request by yutannihilation**
As suggested by https://github.com/extendr/rextendr/issues/10#issuecomment-755374666, this PR adds `--all-features`, though this won't compile on my local (#111)... Can I just merge this and see what will happen?

### CODE REVIEW

**Comment by clauswilke** [comment]
See https://github.com/extendr/extendr/issues/111#issuecomment-755829105. I think you should apply the fix suggested by the compiler, even if the problem doesn't arise in CI.

**Comment by clauswilke** [comment]
It looks to me like we're only testing default features on CI. Maybe this changed when we rewrote the CI scripts? I thought we were testing different feature combinations, but maybe I'm misremembering.

https://github.com/extendr/extendr/blob/7d247b0f029bc5d0c06595558404a36f73a504f8/.github/workflows/test.yml#L133

**Comment by clauswilke** [comment]
And there's another problem: #114 

(Everything else in extendr is now supposed to be thread-safe, so this should be fixed if possible.)

**Comment by yutannihilation** [comment]
Alas, it's tested and failed, but the CI won't fail...

c.f. https://github.com/extendr/extendr/runs/1659948167#step:8:45

It's tested on another matrix here:

https://github.com/extendr/extendr/blob/7d247b0f029bc5d0c06595558404a36f73a504f8/.github/workflows/test.yml#L255-L272

**Comment by clauswilke** [comment]
Oh, Ok, so the test errors out but we aren't notified. Maybe that's a case for @Ilia-Kosenkov.

**Comment by clauswilke** [comment]
I'm not very good with shell scripting but I think the problem is that the return codes from the various `cargo test` invocations are not collected. Normally you'd do something like `command 1 && command 2` to test two separate commands for success. Here we'd have to collect the return values and and them together somehow.

**Comment by Ilia-Kosenkov** [comment]
I will try to fix it later today (or as soon as I can) , I had a similar issue in `libR-sys`.

**Comment by yutannihilation** [comment]
Oh, thanks for taking a look. So, probably we need these lines?

https://github.com/extendr/libR-sys/blob/5ca8d402ff0f56c67544d87ec58fed2d1adbe50c/.github/workflows/test.yml#L140-L143

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation ,
You are correct, this allows to fail fast as soon as one of the builds / tests fail.
`$?` evaluates to either true or false depending on the exit code of last program, and `$LASTEXITCODE` is self-explanatory.

If you would like to implement this, feel free to do so.

**Comment by yutannihilation** [comment]
Thanks, then let me try this!

**Comment by yutannihilation** [comment]
Now I confirmed this will generate `ArrayView1` and `ArrayView2` on the page of `Trait extendr_api::FromRobj`. Let me merge this.

**Comment by yutannihilation** [comment]
Yay!

https://extendr.github.io/extendr/extendr_api/trait.FromRobj.html#impl-FromRobj%3C%27a%3E-for-ArrayView1%3C%27a%2C%20T%3E

**Pull request merged**
