### PR TITLE
Move use extendr_engine inside test! macro

### PR DESCRIPTION
**Pull request by yutannihilation**
Address this concern: https://github.com/extendr/extendr/pull/392#issuecomment-1186392371

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
Is this PR ready or wip?

**Comment by yutannihilation** [comment]
This is ready.

**Review by Ilia-Kosenkov — APPROVED** [review]

**Comment by yutannihilation** [comment]
Thanks!

**Comment by eitsupi** [comment]
Hi, has a version reflecting this change been released yet?
(I'm not sure because there are no tags in this repository.) The following note appears in the package using version 0.3.1 (https://github.com/eitsupi/prqlr/blob/9c8a0330d6e57dd0bb8f4550e1ea159c96b11cca/src/rust/Cargo.toml#L12).

```
* checking compiled code ... NOTE
File 'prqlr/libs/x64/prqlr.dll':
  Found non-API calls to R: 'R_CStackLimit', 'R_CleanTempDir',
    'R_RunExitFinalizers', 'Rf_initialize_R', 'setup_Rmainloop'

Compiled code should not call non-API entry points in R.
```

Thanks for working on this!

**Comment by yutannihilation** [comment]
Not released yet. Sorry for inconvenience. At the moment, you have to use the dev version like my package. Note that I use my branch to test another dev version of libR-sys, but this is not necessary.

c.f. https://github.com/yutannihilation/string2path/blob/6b293f07bf4c0136ace45f7c158dd709163f6099/src/rust/Cargo.toml#L10

I personally consider this is a serious problem that is worth another release, but, since few people here care about CRAN much (and I'm too lazy to explain the details), it's not released yet. Btw, I recently found I have permission on crates.io, so it's possible to release if we agree to release.

**Comment by Ilia-Kosenkov** [comment]
It is possible it has not been released yet. Can you try building your package targeting github versio on of extendr?

**Pull request merged**
