### PR TITLE
Fix compilation with features `result_list` and `result_condition` 

### LINKED ISSUE #650: The `result_list` feature seems broken
See https://github.com/pola-rs/r-polars/issues/418#issuecomment-1783983375

### PR DESCRIPTION
**Pull request by CGMossa**
Fix #650

Unfortunately, we have `result_list` and `result_condition`. These features are not additive, so they don't belong with `full-functionality`. There are three cases: including either, and including neither.

### CODE REVIEW

**Comment by CGMossa** [comment]
These features weren't fully tested and integrated into the codebase. There is a discrepancy between `TryFrom` and `Into` as well, that have to be dealt with somehow.

**Comment by CGMossa** [comment]
@eitupsi here it is.

**Comment by CGMossa** [comment]
@eitsupi here it is! Leave a review if you'd like.

**Comment by eitsupi** [comment]
Thanks!
I tried 0ac58377c50174818e02de54b1032c5f4cb75e4f but it doesn't seem working...

```log
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/into_robj.rs:159:22
       |
   159 |             Ok(x) => list!(ok = x, err = NULL),
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::List;
       |
   
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/into_robj.rs:159:22
       |
   159 |             Ok(x) => list!(ok = x, err = NULL),
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::Robj;
       |
   
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/into_robj.rs:165:17
       |
   165 |                 list!(ok = NULL, err = err_robj)
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::List;
       |
   
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/into_robj.rs:165:17
       |
   165 |                 list!(ok = NULL, err = err_robj)
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::Robj;
       |
   
   error[E0599]: the method `into_robj` exists for type parameter `E`, but its trait bounds were not satisfied
      --> /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/into_robj.rs:161:34
       |
   152 | impl<T, E> From<std::result::Result<T, E>> for Robj
       |         - method `into_robj` not found for this type parameter
   ...
   161 |                 let err_robj = x.into_robj();
       |                                  ^^^^^^^^^ method cannot be called on `E` due to unsatisfied trait bounds
       |
      ::: /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/mod.rs:111:1
       |
   111 | pub struct Robj {
       | ---------------
       | |
       | doesn't satisfy `robj::Robj: From<&E>`
       | doesn't satisfy `robj::Robj: From<&mut E>`
       | doesn't satisfy `robj::Robj: From<E>`
       |
   note: the following trait bounds were not satisfied:
         `robj::Robj: From<&E>`
         `robj::Robj: From<&mut E>`
         `robj::Robj: From<E>`
      --> /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/e1fa539/extendr-api/src/robj/into_robj.rs:203:11
       |
   201 | impl<T> IntoRobj for T
       |         --------     -
   202 | where
   203 |     Robj: From<T>,
       |           ^^^^^^^ unsatisfied trait bound introduced here
   note: the trait `From` must be implemented
      --> /usr/local/rustup/toolchains/nightly-2023-08-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:538:1
       |
   538 | pub trait From<T>: Sized {
       | ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by CGMossa** [comment]
Err. I need to see how you're testing it... I also think I need to make a test for it....

Sorry, I did try my best here. Macros are weird...

**Comment by eitsupi** [comment]
I just tried to build https://github.com/pola-rs/r-polars/commit/a7202a2f5a144a5b0c53e76246ed3e81499e7ba5

**Comment by CGMossa** [comment]
Can you try clean and update?
I tried to compile this, and in the end I managed, but it works on my end?

**Comment by yutannihilation** [comment]
@eitsupi 
I might be wrong, but looking at the `Cargo.lock` in https://github.com/pola-rs/r-polars/commit/a7202a2f5a144a5b0c53e76246ed3e81499e7ba5, it seems it still refers to the HEAD of master (e1fa53998cacb94d4661bb7500c06e1dc9dfb1f2), not this branch.

```
source = "git+https://github.com/extendr/extendr#e1fa53998cacb94d4661bb7500c06e1dc9dfb1f2"
```

**Comment by CGMossa** [comment]
Thanks for the assist @yutannihilation , because otherwise it works on my end....

**Comment by CGMossa** [comment]
Alright. Must inform you that
```
warning: C:\Users\tpb398\Documents\GitHub\r-polars\src\rust\Cargo.toml: unused manifest key: dependencies.extendr-api.ref 
```


```
rustup override set stable-gnu
```

```toml
[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32.static.posix-gcc.exe"
```

**Comment by eitsupi** [comment]
Sorry, it seems my typo was the problem. (`ref` v.s. `rev`)

The compilation error no longer occurs, I think the problem is fixed. Thanks!

**Comment by CGMossa** [comment]
Well if this works, @eitsupi do you mind leaving a review? It would help Ilia's ever growing workload.

**Review by eitsupi — APPROVED** [review]

**Comment by CGMossa** [comment]
@Ilia-Kosenkov the xtasks necessary to make sure this doesn't happen with these features is atrocious. I'll put them in another draft PR, but they need to be command-line-arg gated.

**Comment by Ilia-Kosenkov** [comment]
Sorry, which `xtask` are you referring to?

**Comment by CGMossa** [comment]
We have to run everything with `return_list`, then `return_condition` for both `cargo doc` and `cargo test` to ensure that there are no issues with these. But those are some expensive runs necessary to ensure that this issue doesn't happen again. I wrote them, and used them to verify this, but they are too expensive and not delicate enough. So if you were wondering, I'll have to do that on another PR.

**Comment by Ilia-Kosenkov** [comment]
This feature gate becomes problematic. Maybe we should instead roll it back and introduce options in `#[extendr]`? It is just code-gen that we can control however we want.

**Comment by CGMossa** [comment]
That's going to be another exploration entirely.
Polars depends on this. So I'm inclined to get this merged first. They
depend on commit hashes for extendr.

**Comment by sorhawell** [comment]
> This feature gate becomes problematic. Maybe we should instead roll it back and introduce options in `#[extendr]`? It is just code-gen that we can control however we want.

If you chooses to go down that interesting ally, you may conflict with your own trait system.

Today what ever is returned from an #[extendr]-rust-function/method must implement `Into<Robj>`. There can only be one `impl<T, E> From<std::result::Result<T, E>> for Robj` defined and it must be defined within the extendr crate. This feature gating here ensures there can only be one impl.

Maybe you could let the proc macro call different designated conversions and not only `x.into()` or even user defined conversions.

**Comment by CGMossa** [comment]
We may go down that ally. I will investigate this month. But we merged this feature in, and I would like to have it functioning in at least one commit, so that rpolars will work.

Rust has GATS, so we should be able to make it actually work. And we have IntoRobj, I. E. A custom intermediary trait to facilitate conversions and that can encompass any granularity that we may wish for.

But this PR will stay like this.
If you have more streamlined thoughts about this @sorhawell then I welcome you to write them up. I will be working full time on ExtendR from next week for a month.

**Comment by yutannihilation** [comment]
Okay, this won't work. Is it possible to run only the tests in `extendr-api/src/robj/into_robj.rs`? I'm not sure if `--doc` can specify the specific `impl`, so it might be better to move the doc tests to unit tests.

```
   thread 'robj::into_robj::test::test_collect_rarray_matrix' panicked at extendr-api/src/robj/into_robj.rs:792:13:
  assertion `left == right` failed
    left: list!(ok=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], err=()).set_class(["extendr_result"]
   right: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
```

**Comment by yutannihilation** [comment]
What's the status of this? Do you need any help?

**Comment by CGMossa** [comment]
Err... I forgot about this. Sure, I think you can just push to this PR if you know what needs to be done.

**Comment by yutannihilation** [comment]
Sorry, I don't have such an energy for this... But, I'll try to help you if you need any.

**Comment by CGMossa** [comment]
No worries.

I feel like I don't understand where this error comes from. I don't see it.

But I'll try to figure out what you meant.. No worries at all.

**Comment by yutannihilation** [comment]
I meant using these features make the return type of `Robj::from()` different, so assertions like this fail. I guess the valid tests for the feature are only the doc tests added by the original pull request. But, I don't think doc test can have something like a `cfg` switch, so probably it should be unit tests instead of doc tests.

https://github.com/extendr/extendr/blob/4719dea9a87928b65f50e1a7995e299cd6e72597/extendr-api/src/robj/into_robj.rs#L786C6-L793

**Comment by eitsupi** [comment]
Could you merge this without tests? (there was no test originally, was there?)

**Comment by eitsupi** [comment]
Alternatively, I would recommend revert #473 and removing this feature, as it does not appear to be possible to run tests from this repository.

Don't worry we will fork extendr (again).

**Comment by yutannihilation** [comment]
> there was no test originally, was there?

Yes, there were. #473 did add tests. The problem is that it's never executed in actual. I'm not demanding to write hundreds of tests from scratch. I think it's just moving the doctest added in #473 to unit test under `cfg`.

**Comment by eitsupi** [comment]
#686

**Comment by JosiahParry** [comment]
Closed by #686

**Pull request closed without merging**
