### PR TITLE
Use libR-sys v0.5.0

### PR DESCRIPTION
**Pull request by yutannihilation**

### CODE REVIEW

**Review by CGMossa — APPROVED** [review]
Perfection

**Comment by yutannihilation** [comment]
It seem things are not so easy :)

Maybe I need some tweak on rextendr? I forget everything about what was needed when we updated libR-sys last time...

**Comment by CGMossa** [comment]
Windows failed. First thing to check is length of paths. If it exceeds a
certain threshold then we are in trouble.

**Comment by yutannihilation** [comment]
It seems this problem is related to Rust 1.70. I see such errors like

```
...snip...\std\src\sys\windows/handle.rs:290: undefined reference to `NtWriteFile'
```

I'm wondering why we didn't catch this with the nightly toolchain, but maybe we don't have any CI runner with nightly on Windows...?

**Comment by yutannihilation** [comment]
The line 290 of the fine is this.

https://github.com/rust-lang/rust/blame/1.70.0/library/std/src/sys/windows/handle.rs#L290

This line is not very new. The code has been here from 1 year ago, so I guess this is related to stabilization of some feature. Maybe `OnceCell`?

**Comment by yutannihilation** [comment]
Note: It can be solved by adding `-lntdll`.

**Comment by yutannihilation** [comment]
Windows tests still fail, but let's merge this to let other runners pass.

**Pull request merged**
