### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by yutannihilation**
We now can check these items, right?

### CODE REVIEW

**Comment by andy-thomason** [comment]
Yes! Absolutely.

**Comment by yutannihilation** [comment]
Thanks for confirming!

**Comment by clauswilke** [comment]
In the long run, though, as the project matures, I would probably just delete this roadmap from the README altogether. It's always better to underpromise and overdeliver and roadmaps tend to create the opposite effect.

**Comment by andy-thomason** [comment]
It has probably served its purpose.

**Comment by yutannihilation** [comment]
I agree with your concern on showing the roadmap. But I'd add that the roadmap is probably important if you consider getting funded or sponsored (i.e. GitHub Sponsors), at the risk of overpromising.

I think the README needs an overhaul anyway, considering that in-R usages are described in rextendr's document and each crate now has its own README. I'm wondering what information should be here.

**Comment by andy-thomason** [comment]
Yes. Definitely in need of an overhaul.

I've been looking at sponsorship sources as I intend to leave my current job to focus on teaching and open source.
I may return, at least partially, to academia.

We should set up Github sponsors for the project.

**Comment by yutannihilation** [comment]
Wish you great success! :)

**Pull request merged**
