### PR TITLE
Patch current `extendr`-impl macro

### PR DESCRIPTION
**Pull request by CGMossa**

### CODE REVIEW

**Comment by CGMossa** [comment]
@Ilia-Kosenkov do you know why this is failing?
```
Show testthat output
  find: ‘check’: No such file or directory
```

**Comment by Ilia-Kosenkov** [comment]
I will check.

**Comment by Ilia-Kosenkov** [comment]
Oh you dropped `From` and now itis confused. Even if there is `TryFrom`, `impl`s might not utilize it yet (I do not know).

**Comment by CGMossa** [comment]
Fundamentally, `From<&T> for Robj`, shouldn't be implemented in context of `ExternalPtr`. We are supposed to get the reference from the provided `Robj`, by accessing the stored pointer.
Even a `TryFrom<&T> for Robj` would be wrong as well.

**Comment by Ilia-Kosenkov** [comment]
But how else would you return a `Self` to R?

**Comment by CGMossa** [comment]
There is `From<T> for Robj`. That is the ownership is taken, and the object is "leaked". Now, R owns it. R destroys/drops it. R yields back `Robj` from which we only may extract `&T` and `&mut T`, or any other pointer-type.

**Pull request closed without merging**
