### PR TITLE
Fix compilation with features `result_list` and `result_condition`

### LINKED ISSUE #650: The `result_list` feature seems broken
See https://github.com/pola-rs/r-polars/issues/418#issuecomment-1783983375

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #650, supersedes #652

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks, this is exactly what I meant. But, I have no idea why the integration tests fail...

**Comment by eitsupi** [comment]
Yes, the failed test does not seem to be related to this PR change.

**Comment by yutannihilation** [comment]
> `── Error ('test-optional-features.R:58:3'): Enabling experimental feature raises warning ──`

It seems the test fails here:

https://github.com/extendr/rextendr/blob/be24a8f9e34ceb57630c24f336299bbb73022bee/tests/testthat/test-optional-features.R#L58

**Comment by CGMossa** [comment]
I'm happy that you figured out what to do about this. I tried a few times, and I don't know the result, but clearly I didn't understand or did what was asked.

I'm very thankful that you took my little PR further. Let me know when to approve..

Unfortunately I won't have time this week to solve issues, but maybe in the weekend definitely!

Cheers guys

**Comment by JosiahParry** [comment]
All checks are now passing

**Comment by CGMossa** [comment]
Approving this and merging is kind obnoxious, because I wrote the initial bit. I'll approve and merge, but let us hope it won't cause issues because no one had oversight over me.

**Review by CGMossa — APPROVED** [review]

**Pull request merged**
