### PR TITLE
Using check r package action

### PR DESCRIPTION
**Pull request by Ilia-Kosenkov**
This seems to also fix the issue of testing extendr 0.3.1 (or something else has changed and I am just lucky).

### CODE REVIEW

**Comment by yutannihilation** [comment]
Looks good. Do you see anything that is not ready here?

**Comment by Ilia-Kosenkov** [comment]
Yeah, there is a debug commit enabling CI on all branches I used for testing and I forgot to revert it.  Will do that later when I get to my PC.

**Comment by yutannihilation** [comment]
I see.

**Comment by andy-thomason** [comment]
Looks good. Let me know if you need help with anything. Enjoying the Spanish sunshine until Tuesday.

**Review by yutannihilation — APPROVED** [review]

**Pull request merged**
