### PR TITLE
Let ALTREPs return Rint and Rfloat

### LINKED ISSUE #312: Can AltIntegerImpl::{elt, get_region} return Rint and Rfloat instead of Rust i32 and f64?

### PR DESCRIPTION
**Pull request by yutannihilation**
Close #312

### CODE REVIEW

**Comment by yutannihilation** [comment]
Why can't I call `elt()` directly? I wanted to add some tests on handling missing values,

``` rust
        assert_eq!(obj.elt(9), R!(9.0));
        assert!(obj.elt(10).is_na());
```

but I got this error:

```
error[E0599]: the method `elt` exists for struct `extendr_api::Altrep`, but its trait bounds were not satisfied
   --> extendr-api/tests/altrep_tests.rs:69:24
    |
69  |         assert_eq!(obj.elt(9), R!(9.0));
    |                        ^^^ method cannot be called on `extendr_api::Altrep` due to unsatisfied trait bounds
    |
   ::: /home/yutani/repo/extendr/extendr-api/src/robj/mod.rs:108:1
    |
108 | pub struct Robj {
    | ---------------
    | |
    | doesn't satisfy `extendr_api::Robj: ExactSizeIterator`
    | doesn't satisfy `extendr_api::Robj: Iterator`
    | doesn't satisfy `extendr_api::Robj: extendr_api::AltIntegerImpl`
    | doesn't satisfy `extendr_api::Robj: extendr_api::AltRealImpl`
    |
   ::: /home/yutani/repo/extendr/extendr-api/src/wrapper/altrep.rs:44:1
    |
```

**Comment by andy-thomason** [comment]
You will need to convert the Altrep object to Integer or Doubles before you can access the elements.

currently this is a two stage process but we could short-circuit it.

```
        #[derive(Debug, Clone)]
        struct MyCompactIntRange {
            start: i32,
            len: i32,
            step: i32,
        }

        impl AltrepImpl for MyCompactIntRange {
            fn length(&self) -> usize {
                self.len as usize
            }
        }

        impl AltIntegerImpl for MyCompactIntRange {
            fn elt(&self, index: usize) -> i32 {
                self.start + self.step * index as i32
            }
        }

        let mystate = MyCompactIntRange { start: 0, len: 10, step: 1 };

        let class = Altrep::make_altinteger_class::<MyCompactIntRange>("cir", "mypkg");
        let obj = Altrep::from_state_and_class(mystate, class, false);

        let robj = Robj::from(obj.clone());
        let integers : Integers = robj.try_into()?;
        assert_eq!(integers.elt(0), 0);
```

**Comment by andy-thomason** [comment]
We should perhaps make the from_state_and_class a method of Integer and ditch the Altrep wrapper.

**Comment by yutannihilation** [comment]
Ahh, makes sense, thanks! 

> We should perhaps make the from_state_and_class a method of Integer and ditch the Altrep wrapper.

This sounds convenient.

**Comment by yutannihilation** [comment]
32-bit Windows fails with the altreal test, so I guess I'm handling f64 improperly, but I have no idea...

**Comment by andy-thomason** [comment]
I'm wondering if `Win32` is reinterpreting the NAN which is the `Rfloat.na()` value.

The default behaviour should be to pass it through.

Maybe just making the NA check conditional on the CPU type would be sensible.

**Comment by Ilia-Kosenkov** [comment]
32-bit win tests from `master` fail on my local machine, I suggest running the pipeline on `master` and see if it works.

**Comment by yutannihilation** [comment]
Oh, really? The most recent commit passes, so I think the current `master` should be fine.

https://github.com/extendr/extendr/commit/6f58340130310a18a6349099c92cedf92d6f01b7

(Btw, I'm switching my main machine to Windows again, so I'll be quicker on testing this kind of things!)

**Comment by Ilia-Kosenkov** [comment]
I am currently updating R 4.1.1 -> 4.1.2 and also pulling the latest rust toolchains. I will post the result of local tests if they fail.

**Comment by Ilia-Kosenkov** [comment]
Still fails `na` tests. AFAIK we do not run this particular pipeline, because doctests are not supported in cross-compilation regime, but only as a nightly feature. I can probably investigate what exact value is used as `NA` when it is 32 bit.

```pwsh
@("Rscript.exe -e `"R.version`"", "cargo --version", "git log -n 1 --oneline") | % {iex $_ ; ""} > info.dat
```
<details>
<summary>info.dat</summary>

```
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 

cargo 1.58.0-nightly (94ca096af 2021-10-29)

6f583401 Fix clippy warnings (#319)
```

</details>

```pwsh
 (cargo test --target i686-pc-windows-gnu
 -Zdoctest-xcompile --features tests-all --manifest-path .\extendr-api\Cargo.toml)  2>&1 > log.dat
```

<details>
<summary>log.dat</summary>

```
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.24
   Compiling memchr v2.3.4
   Compiling unicode-xid v0.2.1
   Compiling glob v0.3.0
   Compiling cc v1.0.66
   Compiling libc v0.2.81
   Compiling version_check v0.9.2
   Compiling lazy_static v1.4.0
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling quick-error v1.2.3
   Compiling cfg-if v0.1.10
   Compiling regex-syntax v0.6.21
   Compiling vec_map v0.8.2
   Compiling autocfg v1.0.1
   Compiling bindgen v0.53.3
   Compiling strsim v0.8.0
   Compiling shlex v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling lazycell v1.3.0
   Compiling syn v1.0.55
   Compiling serde_derive v1.0.118
   Compiling serde v1.0.118
   Compiling extendr-engine v0.2.0 (D:\OneDrive\Development\OSS\extendr\extendr-engine)
   Compiling rawpointer v0.2.1
   Compiling extendr-api v0.2.0 (D:\OneDrive\Development\OSS\extendr\extendr-api)
   Compiling paste v1.0.5
   Compiling thread_local v1.0.1
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling matrixmultiply v0.3.1
   Compiling nom v5.1.2
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling clang-sys v0.29.3
   Compiling which v3.1.1
   Compiling aho-corasick v0.7.15
   Compiling quote v1.0.8
   Compiling libloading v0.5.2
   Compiling regex v1.4.2
   Compiling num-complex v0.4.0
   Compiling ndarray v0.15.3
   Compiling cexpr v0.4.0
   Compiling winapi-util v0.1.5
   Compiling atty v0.2.14
   Compiling clap v2.33.3
   Compiling termcolor v1.1.2
   Compiling env_logger v0.7.1
   Compiling extendr-macros v0.2.0 (D:\OneDrive\Development\OSS\extendr\extendr-macros)
   Compiling libR-sys v0.2.2
warning: unused variable: `test`
  --> extendr-api\tests\serializer_tests.rs:88:17
   |
88 |             let test = Test {
   |                 ^^^^ help: if this is intentional, prefix it with an underscore: `_test`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `expected`
   --> extendr-api\tests\serializer_tests.rs:115:17
    |
115 | ...   let expected = list!(int=1, seq=list!(null = (), symbol = (), pairlist = (), function = (), rstr = (), integer = (), real = (), lis...
    |           ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_expected`

warning: `extendr-api` (test "serializer_tests") generated 2 warnings
    Finished test [unoptimized + debuginfo] target(s) in 19.47s
     Running unittests (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\extendr_api-a3264f1906e84f55.exe)

running 34 tests
test robj_ndarray::test_round_trip ... ok
test tests::pairlist_macro_works ... ok
test tests::r_output_test ... ok
test robj::tests::test_debug ... ok
test tests::test_na_str ... ok
test tests::slice_test ... ok
test wrapper::doubles::tests::from_iterator ... ok
test wrapper::doubles::tests::from_values_short ... ok
test wrapper::doubles::tests::iter ... ok
test wrapper::doubles::tests::iter_mut ... ok
test wrapper::doubles::tests::new ... ok
test wrapper::integers::tests::from_iterator ... ok
test wrapper::integers::tests::from_values_long ... ok
test wrapper::integers::tests::from_values_short ... ok
test wrapper::integers::tests::iter ... ok
test wrapper::integers::tests::iter_mut ... ok
test wrapper::integers::tests::new ... ok
test wrapper::matrix::matrix_ops ... ok
test wrapper::symbol::test::test_constant_symbols ... ok
test robj_ndarray::test_from_robj ... ok
test ownership::test::basic_test ... ok
test robj::tests::input_iterator_test ... ok
test ownership::test::collection_test ... ok
test tests::big_r_macro_works ... ok
test robj_ndarray::test_to_robj ... ok
test robj::tests::test_from_robj ... ok
test robj::tests::parse_test ... ok
test robj::tests::output_iterator_test ... ok
test tests::class_wrapper_test ... ok
test robj::tests::test_try_from_robj ... ok
test tests::metadata_test ... ok
test robj::tests::test_to_robj ... ok
test tests::export_test ... ok
test wrapper::doubles::tests::from_values_long ... ok

test result: ok. 34 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.07s

     Running tests\altrep_tests.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\altrep_tests-691a7f1d935273c3.exe)

running 6 tests
test test_altraw ... ok
test test_altstring ... ok
test test_altreal ... ok
test test_altlogical ... ok
test test_altinteger ... ok
test test_altcomplex ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.17s

     Running tests\call_tests.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\call_tests-074eeb18d3522ab5.exe)

running 2 tests
test formula_test ... ok
test special_test ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.14s

     Running tests\extendr_macro.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\extendr_macro-af9d835e00314816.exe)

running 2 tests
test test_call_macro ... ok
test tests_with_successful_outcomes ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.14s

     Running tests\externalptr_test.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\externalptr_test-c6d26cdbe10cc309.exe)

running 2 tests
test test_externalptr ... ok
test test_externalptr_drop ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

     Running tests\graphics_tests.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\graphics_tests-0d9c61cfe5f9aadd.exe)

running 1 test
test graphics_test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

     Running tests\scalar_tests.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\scalar_tests-ed5a064ee06afeb8.exe)

running 4 tests
test test_rfloat_opassign ... ok
test test_rfloat ... ok
test test_rint ... ok
test test_rint_opassign ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests\serializer_tests.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\serializer_tests-9dea4f848b395ee4.exe)

running 3 tests
test test::test_serialize_robj ... ok
test test::test_serialize_struct ... ok
test test::test_serialize_enum ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

     Running tests\vector_tests.rs (C:\Users\[redacted]\AppData\Local\Temp\cargo_temp\i686-pc-windows-gnu\debug\deps\vector_tests-b2486fa52eff4a18.exe)

running 1 test
test test_strings ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.13s

   Doc-tests extendr-api

running 174 tests
test src\graphics\mod.rs - graphics::Context::font_face (line 255) ... ignored
test src\graphics\mod.rs - graphics::Context::line_end (line 203) ... ignored
test src\graphics\mod.rs - graphics::Context::line_join (line 218) ... ignored
test src\graphics\mod.rs - graphics::Context::line_type (line 179) ... ignored
test src\functions.rs - functions::local_var (line 32) - compile ... ok
test src\functions.rs - functions::parse (line 202) ... ok
test src\functions.rs - functions::current_env (line 79) ... ok
test src\functions.rs - functions::find_namespace (line 60) ... ok
test src\functions.rs - functions::new_env (line 109) ... ok
test src\lib.rs - (line 14) ... ignored
test src\functions.rs - functions::eval_string_with_params (line 249) ... ok
test src\functions.rs - functions::find_namespaced_function (line 277) ... ok
test src\functions.rs - functions::base_namespace (line 149) ... ok
test src\lib.rs - (line 32) ... ignored
test src\functions.rs - functions::global_function (line 45) ... ok
test src\functions.rs - functions::global_var (line 8) ... ok
test src\lang_macros.rs - lang_macros::lang (line 98) ... ok
test src\functions.rs - functions::eval_string (line 225) ... ok
test src\functions.rs - functions::namespace_registry (line 161) ... ok
test src\iter.rs - iter::StrIter (line 10) ... ok
test src\iter.rs - iter::Robj::as_str_iter (line 143) ... ok
test src\functions.rs - functions::base_env (line 136) ... ok
test src\functions.rs - functions::global_env (line 91) ... ok
test src\na.rs - na::f64 (line 9) ... ok
test src\na.rs - na::i32 (line 25) ... ok
test src\na.rs - na::Bool (line 41) ... ok
test src\na.rs - na::&'_str (line 58) ... ok
test src\lib.rs - (line 166) ... ok
test src\rmacros.rs - rmacros::data_frame (line 119) ... ok
test src\lib.rs - (line 208) ... ok
test src\rmacros.rs - rmacros::factor (line 142) ... ok
test src\lib.rs - (line 136) ... ok
test src\lib.rs - (line 176) ... ok
test src\lib.rs - (line 101) ... ok
test src\rmacros.rs - rmacros::global (line 62) ... ok
test src\lib.rs - (line 115) ... ok
test src\lib.rs - (line 39) ... ok
test src\rmacros.rs - rmacros::var (line 40) - compile ... ok
test src\rmacros.rs - rmacros::list (line 97) ... ok
test src\lib.rs - (line 80) ... ok
test src\robj\into_robj.rs - robj::into_robj::Robj (line 27) ... ok
test src\robj\mod.rs - robj::Robj::as_integer (line 527) ... ok
test src\rmacros.rs - rmacros::sym (line 79) ... ok
test src\robj\mod.rs - robj::Robj (line 79) ... ok
test src\robj\mod.rs - robj::Robj::as_integer_slice_mut (line 426) ... ok
test src\robj\mod.rs - robj::Robj::as_integer_vector (line 302) ... ok
test src\robj\mod.rs - robj::Robj::as_bool (line 565) ... ok
test src\robj\mod.rs - robj::Robj::as_integer_slice (line 284) ... ok
test src\robj\mod.rs - robj::Robj::as_logical (line 584) ... ok
test src\rmacros.rs - rmacros::r (line 10) ... ok
test src\robj\mod.rs - robj::Robj (line 91) ... ok
test src\robj\mod.rs - robj::Robj::as_logical_iter (line 342) ... ok
test src\robj\mod.rs - robj::Robj::as_logical_slice (line 316) ... ok
test src\robj\mod.rs - robj::Robj (line 43) ... ok
test src\robj\into_robj.rs - robj::into_robj::RobjItertools::collect_robj (line 397) ... ok
test src\robj\mod.rs - robj::Robj::as_logical_vector (line 330) ... ok
test src\robj\mod.rs - robj::Robj::as_raw_slice_mut (line 455) ... ok
test src\robj\mod.rs - robj::Robj::as_real (line 546) ... ok
test src\robj\mod.rs - robj::Robj::as_raw_slice (line 413) ... ok
test src\robj\mod.rs - robj::Robj::as_real_iter (line 383) ... ok
test src\robj\mod.rs - robj::Robj::class (line 852) ... ok
test src\robj\mod.rs - robj::Robj::as_str (line 500) ... ok
test src\robj\mod.rs - robj::Robj::eval (line 603) ... ok
test src\robj\mod.rs - robj::Robj::as_string_vector (line 470) ... ok
test src\robj\mod.rs - robj::Robj::eval_blind (line 637) ... ok
test src\robj\mod.rs - robj::Robj::as_real_slice_mut (line 441) ... ok
test src\robj\mod.rs - robj::Robj::as_str_vector (line 486) ... ok
test src\robj\mod.rs - robj::Robj::dimnames (line 835) ... ok
test src\robj\mod.rs - robj::Robj::dim (line 817) ... ok
test src\robj\mod.rs - robj::Robj::as_real_vector (line 401) ... ok
test src\robj\mod.rs - robj::Robj::eval_with_env (line 616) ... ok
test src\robj\mod.rs - robj::Robj::as_real_slice (line 365) ... ok
test src\robj\mod.rs - robj::Robj::get_attrib (line 718) ... ok
test src\robj\mod.rs - robj::Robj::inherits (line 891) ... ok
test src\robj\operators.rs - robj::operators::Robj::call (line 94) ... ok
test src\robj\mod.rs - robj::Robj::set_attrib (line 749) ... ok
test src\robj\mod.rs - robj::Robj::is_empty (line 243) ... ok
test src\robj\mod.rs - robj::Robj::names (line 773) ... ok
test src\robj\mod.rs - robj::Robj::len (line 230) ... ok
test src\robj\operators.rs - robj::operators::Robj::div (line 218) ... ok
test src\robj\operators.rs - robj::operators::Robj::dollar (line 10) ... ok
test src\robj\operators.rs - robj::operators::Robj::add (line 122) ... ok
test src\robj\mod.rs - robj::Robj::set_class (line 872) ... ok
test src\robj\mod.rs - robj::Robj::is_na (line 257) ... ok
test src\robj\mod.rs - robj::Robj::levels (line 907) ... ok
test src\robj\mod.rs - robj::Robj::set_names (line 793) ... ok
test src\robj\mod.rs - robj::Robj::rtype (line 146) ... ok
test src\robj\operators.rs - robj::operators::Robj::double_colon (line 77) ... ok
test src\robj\rinternals.rs - robj::rinternals::Robj::find_function (line 121) ... ok
test src\scalar\rfloat.rs - scalar::rfloat::Rfloat (line 35) ... ok
test src\scalar\rint.rs - scalar::rint::Rint (line 20) ... ok
test src\scalar\rfloat.rs - scalar::rfloat::Rfloat (line 35) ... ok
test src\thread_safety.rs - thread_safety::catch_r_error (line 101) ... ignored
test src\scalar\rfloat.rs - scalar::rfloat::Rfloat::sum (line 44) ... ok
test src\robj\rinternals.rs - robj::rinternals::Robj::eval_promise (line 214) ... ok
test src\scalar\rint.rs - scalar::rint::Rint (line 20) ... ok
test src\scalar\rfloat.rs - scalar::rfloat::Rfloat (line 35) ... FAILED
test src\robj\rinternals.rs - robj::rinternals::Robj::find_var (line 167) ... ok
test src\robj\operators.rs - robj::operators::Robj::tilde (line 60) ... ok
test src\robj\operators.rs - robj::operators::Robj::sub (line 154) ... ok
test src\scalar\rfloat.rs - scalar::rfloat::Rfloat (line 35) ... ok
test src\robj\operators.rs - robj::operators::Robj::index (line 44) ... ok
test src\scalar\rint.rs - scalar::rint::Rint (line 20) ... ok
test src\robj\operators.rs - robj::operators::Robj::mul (line 186) ... ok
test src\robj\operators.rs - robj::operators::Robj::slice (line 28) ... ok
test src\scalar\rint.rs - scalar::rint::Rint (line 20) ... ok
test src\wrapper\doubles.rs - wrapper::doubles::Doubles::new (line 24) ... ok
test src\wrapper\environment.rs - wrapper::environment::Environment::local (line 162) ... ok
test src\scalar\rint.rs - scalar::rint::Rint::sum (line 24) ... ok
test src\wrapper\doubles.rs - wrapper::doubles::Doubles::elt (line 25) ... FAILED
test src\wrapper\environment.rs - wrapper::environment::Environment::new_with_capacity (line 26) ... ok
test src\wrapper\environment.rs - wrapper::environment::Environment::new_with_parent (line 10) ... ok
test src\wrapper\environment.rs - wrapper::environment::Environment::from_pairs (line 46) ... ok
test src\wrapper\environment.rs - wrapper::environment::Environment::set_local (line 142) ... ok
test src\thread_safety.rs - thread_safety::single_threaded (line 21) ... ok
test src\wrapper\expr.rs - wrapper::expr::Expression::from_values (line 10) ... ok
test src\wrapper\environment.rs - wrapper::environment::Environment::names (line 129) ... ok
test src\wrapper\doubles.rs - wrapper::doubles::Doubles (line 8) ... ok
test src\serializer.rs - serializer::to_robj (line 66) ... ok
test src\wrapper\environment.rs - wrapper::environment::EnvIter (line 188) ... ok
test src\wrapper\externalptr.rs - wrapper::externalptr::ExternalPtr (line 6) ... ok
test src\wrapper\integers.rs - wrapper::integers::Integers::new (line 24) ... ok
test src\wrapper\function.rs - wrapper::function::Function::from_parts (line 33) ... ok
test src\wrapper\function.rs - wrapper::function::Function::call (line 55) ... ok
test src\wrapper\lang.rs - wrapper::lang::Language (line 4) ... ok
test src\wrapper\list.rs - wrapper::list::List::new (line 16) ... ok
test src\wrapper\list.rs - wrapper::list::List::from_values (line 30) ... ok
test src\wrapper\integers.rs - wrapper::integers::Integers::elt (line 25) ... ok
test src\wrapper\list.rs - wrapper::list::List::values (line 67) ... ok
test src\wrapper\list.rs - wrapper::list::List::into_iter (line 100) ... ok
test src\wrapper\integers.rs - wrapper::integers::Integers (line 8) ... ok
test src\wrapper\function.rs - wrapper::function::Function (line 4) ... ok
test src\wrapper\list.rs - wrapper::list::List::iter (line 80) ... ok
test src\wrapper\list.rs - wrapper::list::FromList (line 187) ... ok
test src\wrapper\list.rs - wrapper::list::FromList<Vec<T>>::try_from (line 205) ... ok
test src\wrapper\list.rs - wrapper::list::ListIter::try_from (line 226) ... ok
test src\wrapper\list.rs - wrapper::list::ListIter (line 115) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_char (line 196) ... ok
test src\wrapper\list.rs - wrapper::list::Robj::from (line 242) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_function (line 292) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_environment (line 276) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_list (line 249) ... ok
test src\wrapper\nullable.rs - wrapper::nullable::Nullable (line 4) ... ok
test src\wrapper\nullable.rs - wrapper::nullable::Nullable<T>::from_robj (line 41) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_symbol (line 184) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_raw (line 208) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_expression (line 262) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_language (line 221) ... ok
test src\wrapper\nullable.rs - wrapper::nullable::Robj::from (line 66) ... ok
test src\wrapper\matrix.rs - wrapper::matrix::RArray (line 8) ... ok
test src\wrapper\matrix.rs - wrapper::matrix::RArray<T,[usize;2]>::index_mut (line 331) ... ok
test src\wrapper\matrix.rs - wrapper::matrix::RArray<T,[usize;2]>::index (line 311) ... ok
test src\wrapper\mod.rs - wrapper::Robj::as_pairlist (line 235) ... ok
test src\wrapper\promise.rs - wrapper::promise::Promise::eval (line 64) ... ok
test src\wrapper\raw.rs - wrapper::raw::Raw::from_bytes (line 28) ... ok
test src\wrapper\s4.rs - wrapper::s4::S4::has_slot (line 104) ... ok
test src\wrapper\s4.rs - wrapper::s4::S4::set_class (line 14) ... ok
test src\wrapper\primitive.rs - wrapper::primitive::Primitive::from_string (line 21) ... ok
test src\wrapper\promise.rs - wrapper::promise::Promise::from_parts (line 11) ... ok
test src\wrapper\rstr.rs - wrapper::rstr::Rstr (line 7) ... ok
test src\wrapper\pairlist.rs - wrapper::pairlist::PairlistIter (line 92) ... ok
test src\wrapper\pairlist.rs - wrapper::pairlist::Pairlist::from_pairs (line 17) ... ok
test src\wrapper\pairlist.rs - wrapper::pairlist::Pairlist::into_iter (line 159) ... ok
test src\wrapper\s4.rs - wrapper::s4::S4::get_slot (line 47) ... ok
test src\wrapper\s4.rs - wrapper::s4::S4::set_slot (line 74) ... ok
test src\wrapper\primitive.rs - wrapper::primitive::Primitive (line 6) ... ok
test src\wrapper\raw.rs - wrapper::raw::Raw (line 5) ... ok
test src\wrapper\pairlist.rs - wrapper::pairlist::Pairlist::iter (line 58) ... ok
test src\wrapper\s4.rs - wrapper::s4::S4::new (line 30) ... ok
test src\wrapper\strings.rs - wrapper::strings::Strings::new (line 19) ... ok
test src\wrapper\symbol.rs - wrapper::symbol::Symbol::from_string (line 21) ... ok
test src\wrapper\symbol.rs - wrapper::symbol::Symbol (line 5) ... ok
test src\wrapper\strings.rs - wrapper::strings::Strings::from_values (line 33) ... ok
test src\wrapper\symbol.rs - wrapper::symbol::Symbol::as_str (line 46) ... ok

failures:

---- src\scalar\rfloat.rs - scalar::rfloat::Rfloat (line 35) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: (<Rfloat>::na()).is_na()', src\scalar\rfloat.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


---- src\wrapper\doubles.rs - wrapper::doubles::Doubles::elt (line 25) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: vec.elt(10).is_na()', src\wrapper\doubles.rs:9:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src\scalar\rfloat.rs - scalar::rfloat::Rfloat (line 35)
    src\wrapper\doubles.rs - wrapper::doubles::Doubles::elt (line 25)

test result: FAILED. 165 passed; 2 failed; 7 ignored; 0 measured; 0 filtered out; finished in 32.40s

error: test failed, to rerun pass '--doc'


```

</details>

**Comment by yutannihilation** [comment]
> because doctests are not supported in cross-compilation regime

Ah, I forgot this, thanks.

I think we can just skip the failing test for now, and address the problem in another pull request.

**Comment by yutannihilation** [comment]
I disabled the test on 32-bit Windows and filed a new issue https://github.com/extendr/extendr/issues/321. Apart from this problem, this pull request should be ready for review now.

**Review by Ilia-Kosenkov — APPROVED** [review]

**Pull request merged**
