### PR TITLE
Check code formatting

### LINKED ISSUE #85: Code formatting
I saw a lot of irrelevant changes on #84 due to auto-formatting. Can we follow the default of `cargo fmt` and check it on CI?

c.f. https://github.com/dimforge/nalgebra/blob/d8fa3ff24147dee0c0b481881aad1c2890fad942/.circleci/config.yml#L13-L22

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #85

We might also want to check `cargo clippy` as suggested on #54, but ~~I disabled it for now~~ (edit: I removed these lines). Let's do it in another pull request because it might require some efforts to erase all the warnings.

### CODE REVIEW

**Comment by yutannihilation** [comment]
Confirmed the CI runner detects code formatting diffs.

https://github.com/extendr/extendr/pull/122/checks?check_run_id=1672247049

@andy-thomason @clauswilke
Could you check whether you feel comfortable with the changes by `cargo fmt`? If we need some tweak on the formatting rule, I'll search for some nice option.

I can merge this only when there are no other pull requests (currently #121) are going, so I'm not in a hurry.

**Comment by clauswilke** [comment]
I'm fine with this.

**Review by clauswilke — APPROVED** [review]

**Comment by andy-thomason** [comment]
Go ahead. Good idea.

**Review by andy-thomason — APPROVED** [review]

**Comment by yutannihilation** [comment]
Thanks for merging!

**Pull request merged**
