### PR TITLE
Install system dependencies on Linux

### LINKED ISSUE #193: Integration tests are failing on R devel due to dependency changes in rextendr
Some dependencies are not getting resolved when trying to install rextendr under R devel:
https://github.com/extendr/extendr/runs/2119084113?check_suite_focus=true

@Ilia-Kosenkov Could you take a look?

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #193 

PowerShell version of this:

https://github.com/extendr/rextendr/blob/def4813dd003efaa9ea7b7b03cbc625c22dcd651/.github/workflows/R-CMD-check.yaml#L76-L82

### CODE REVIEW

**Comment by yutannihilation** [comment]
Hmm, it seems `remotes::system_requirements()` doesn't care about non-direct Suggests dependency... Are there no choice other than to specify libcurl directly...?

```
PS /home/yutani/repo/extendr> Rscript -e "writeLines(remotes::system_requirements('ubuntu', '20.04', path = 'tests/extendrtests'))"
apt-get install -y rustc
apt-get install -y cargo
apt-get install -y libicu-dev
apt-get install -y pandoc
```

Btw, it's a bit annoying `apt-get` installs rustc and cargo.

**Comment by clauswilke** [comment]
How does this work when checking regular R packages? We don't appear to have any problems here:
https://github.com/extendr/rextendr/blob/main/.github/workflows/R-CMD-check.yaml

**Comment by clauswilke** [comment]
Ah, I see. We need the system requirements for rextendr, not for extendrtests.

``` r
remotes::system_requirements("ubuntu", "20.04", "~/github/rextendr")
#>  [1] "apt-get install -y rustc"               
#>  [2] "apt-get install -y cargo"               
#>  [3] "apt-get install -y libcurl4-openssl-dev"
#>  [4] "apt-get install -y libssl-dev"          
#>  [5] "apt-get install -y git"                 
#>  [6] "apt-get install -y libicu-dev"          
#>  [7] "apt-get install -y pandoc"              
#>  [8] "apt-get install -y libxml2-dev"         
#>  [9] "apt-get install -y make"                
#> [10] "apt-get install -y libgit2-dev"
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by yutannihilation** [comment]
Ah, I see. Sorry, I was confused, I thought extendrtests depends on rextendr, but it doesn't...

**Comment by clauswilke** [comment]
Yup, works now.

**Comment by yutannihilation** [comment]
May I merge this?

**Review by clauswilke — APPROVED** [review]

**Comment by yutannihilation** [comment]
Thanks.

**Pull request merged**
