### PR TITLE
Prepare metadata for release

### PR DESCRIPTION
**Pull request by multimeric**
* Bump versions for release
* Add myself as author

Depends on https://github.com/extendr/libR-sys/issues/115

### CODE REVIEW

**Comment by multimeric** [comment]
Do we need anything else for release that I'm missing?

**Comment by CGMossa** [comment]
Also make a `cargo publish --dry-run` to see what happens with that.

**Comment by multimeric** [comment]
```bash
$ cargo publish --dry-run -p extendr-engine 
    Updating crates.io index
   Packaging extendr-engine v0.4.0 (/home/migwell/Programming/extendr/extendr-engine)
   Verifying extendr-engine v0.4.0 (/home/migwell/Programming/extendr/extendr-engine)
   Compiling libR-sys v0.4.0
   Compiling extendr-engine v0.4.0 (/home/migwell/Programming/extendr/target/package/extendr-engine-0.4.0)
    Finished dev [unoptimized + debuginfo] target(s) in 1.63s
   Uploading extendr-engine v0.4.0 (/home/migwell/Programming/extendr/extendr-engine)
warning: aborting upload due to dry run
$ cargo publish --dry-run -p extendr-macros 
    Updating crates.io index
   Packaging extendr-macros v0.4.0 (/home/migwell/Programming/extendr/extendr-macros)
   Verifying extendr-macros v0.4.0 (/home/migwell/Programming/extendr/extendr-macros)
  Downloaded proc-macro2 v1.0.51
  Downloaded syn v1.0.109
  Downloaded 2 crates (279.4 KB) in 1.19s
   Compiling proc-macro2 v1.0.51
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.109
   Compiling extendr-macros v0.4.0 (/home/migwell/Programming/extendr/target/package/extendr-macros-0.4.0)
    Finished dev [unoptimized + debuginfo] target(s) in 8.71s
   Uploading extendr-macros v0.4.0 (/home/migwell/Programming/extendr/extendr-macros)
warning: aborting upload due to dry run
$ cargo publish --dry-run -p extendr-api
    Updating crates.io index
   Packaging extendr-api v0.4.0 (/home/migwell/Programming/extendr/extendr-api)
   Verifying extendr-api v0.4.0 (/home/migwell/Programming/extendr/extendr-api)
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `extendr-engine = "^0.4.0"`
  candidate versions found which didn't match: 0.3.1, 0.3.0, 0.2.0
  location searched: crates.io index
  required by package `extendr-api v0.4.0 (/home/migwell/Programming/extendr/target/package/extendr-api-0.4.0)`
```

**Review by Ilia-Kosenkov — APPROVED** [review]
Long overdue, you should have been on the list long time ago. Welcome aboard, officially :)

**Comment by yutannihilation** [comment]
Note that incrementing the version numbers is supposed to be handled by `cargo-workspace` in the current guide. But, this doesn't work anyway because we would have to push without approval, which violates the branch protection rule.

https://github.com/extendr/extendr/blob/master/MAINTAINERS_GUIDE.md

I think we'll need proper guidance that matches the current workflow, but I think we should delete this guide to avoid confusion. Will create a pr.

**Comment by multimeric** [comment]
Thanks, please do edit/rewrite the guide.

**Pull request merged**
