### PR TITLE
Implement Device::close()

### LINKED ISSUE #299: Implement <Device>::close()
I think `dev.new()` needs to be called with `R!` ayway, but probably `dev.off()` can be done via C API; we can probably use `GEkillDevice`.

https://github.com/wch/r-source/blob/a7671ab01ac59e08e47dfa0aac0355739be8f0fe/src/library/grDevices/src/devices.c#L109-L114
https://github.com/wch/r-source/blob/a7671ab01ac59e08e47dfa0aac0355739be8f0fe/src/main/devices.c#L332-L335

### PR DESCRIPTION
**Pull request by yutannihilation**
Close #299 

I chose `close()` because `off()` might be confusing with `mode_off()`, but I'm open to any suggestions.

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
It feels like `Device` can make use of `Drop`.  In my understanding, `Drop` is designed for managing limited resources, and works well with Rust lifetimes. This will give us a failsafe mechanism -- any `Device` will be eventually `drop()`ed once all its references are out of scope.
Of course, *if* there are no caveats and *if* `Drop` is suitable for our task.

**Comment by yutannihilation** [comment]
Hm, sounds fair, thanks. I just wanted to moving away from using `R!("dev.off()")`, but it seems we'll want to move to "guard model", which we discussed on https://github.com/extendr/extendr/issues/297#issuecomment-941048527, anyway. I'm closing this for now. Let's discuss there.

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation, You should not close this PR IMO, perhaps I should not have started the discussion here and discouraged you. 

I believe it is a good solution for a problem for now, and it implements an obviously missing functionality, so I suggest to re-open it. 

I will move the broader discussion to the mentioned issue.

**Comment by yutannihilation** [comment]
No worries, honestly, I wasn't motivated much to write this pull request. It's just that, because #299 is the issue I filed, I thought it's me who should fix it. 

Actually, on implementing this, I feel I'm getting lost in the graphic APIs in that what `dev.off()` does. I should have figured it out first before diving into this...

**Pull request closed without merging**
