### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by clauswilke**
Contributing guide and code of conduct, copied from libR-sys.

### CODE REVIEW

**Comment by clauswilke** [comment]
I accidentally picked up some unrelated commits. Will fix that soon.

**Comment by clauswilke** [comment]
@yutannihilation This should be the same as for libR-sys. Would you mind giving it a quick read-through to make sure I didn't mess something up?

**Review by andy-thomason — APPROVED** [review]

**Comment by clauswilke** [comment]
I have merged this. If there are any issues we can always fix later.

**Comment by yutannihilation** [comment]
Looks good!

**Pull request merged**
