### PR TITLE
Add support for passing matrices via ArrayView2

### PR DESCRIPTION
**Pull request by hobofan**
I hope that's an acceptable implementation for matrices.

I tried to go a similar route as the conversion to ArrayView1 (via AsTypedSlice), but wasn't really to get something going via that route.

Looking forward to your feedback!

PS: Awesome crate! It's been a joy using it so far, even in it's early stage! :)

### CODE REVIEW

**Comment by clauswilke** [comment]
I have no particular opinion on the implementation (I'll let others comment on that), but I'd like to point out that it's always a good idea to add unit tests for each new feature that gets added.

**Comment by hobofan** [comment]
Good point! Added some tests, similar to the ones of ArrayView1.

**Comment by clauswilke** [comment]
Thanks for adding the tests! I would suggest adding one more test that tests something other than a 1x1 matrix. Maybe 2x3 with different values in the cells, to make sure there's no mixup with rows and columns.

**Comment by hobofan** [comment]
Added a test for that :)

**Comment by clauswilke** [comment]
Thanks!

**Review by clauswilke — APPROVED** [review]

**Review by andy-thomason — APPROVED** [review]
Excellent. Nice to see eval_string in action in the tests.

**Pull request merged**
