### PR TITLE
Add `names<-`,  `dim<-` and `dimnames<-` to `RArray` and friends

### PR DESCRIPTION
**Pull request by CGMossa**

### CODE REVIEW

**Comment by JosiahParry** [comment]
Looks simple enough! We're missing integration tests. Give me a moment to give that a shot.

**Comment by JosiahParry** [comment]
Note that this PR as it stands _does not_ fetch column and row names. There is a PR at https://github.com/extendr/extendr/pull/800 that addresses this.

**Comment by JosiahParry** [comment]
If you want to use this PR only, I think its important we snag the integration tests from #800 as well

**Comment by JosiahParry** [comment]
booyah!

**Comment by JosiahParry** [comment]
This passes the CI but it doesn't have integration tests so we cannot merge

**Comment by CGMossa** [comment]
@JosiahParry I've resolved the issues and tests pass. Do you mind reviewing again?

**Comment by JosiahParry** [comment]
Oof. Wev'e got conflicts.

**Comment by JosiahParry** [comment]
I've resolved conflicts but the snapshots may not be fixed

**Comment by JosiahParry** [comment]
Finally CI worked.

**Review by JosiahParry — APPROVED** [review]

**Pull request merged**
