### PR TITLE
Update libR-sys to v0.6.0

### PR DESCRIPTION
**Pull request by yutannihilation**
Close https://github.com/extendr/extendr/issues/580

### CODE REVIEW

**Comment by yutannihilation** [comment]
The failure on Windows-oldrel seems related to ndarray feature.

`  = note: x86_64-w64-mingw32.static.posix-gcc.exe: error: C:/Users/runneradmin/AppData/Local/Temp/Rtmp4umJGk/working_dir/RtmpEdhhH6/file140c5226deb/target\x86_64-pc-windows-gnu\debug\deps\ndarray_example77009d8b8404fecef8caf59b232f854830.ndarray_example77009d8b8404fecef8caf59b232f854830.89c8dac2a25d80e4-cgu.10.rcgu.o: No such file or directory`

I believe the failure isn't related to updating libR-sys, because the diff of the bindings is only the version header.

```
❯ git diff v0.5.0...v0.6.0 .\bindings\bindings-windows-x86_64-R4.2.rs
diff --git a/bindings/bindings-windows-x86_64-R4.2.rs b/bindings/bindings-windows-x86_64-R4.2.rs
index 4f37ff4..8ac2a52 100644
--- a/bindings/bindings-windows-x86_64-R4.2.rs
+++ b/bindings/bindings-windows-x86_64-R4.2.rs
@@ -1,6 +1,6 @@
 /* automatically generated by rust-bindgen 0.64.0 */

-/* libR-sys version: 0.5.0 */
+/* libR-sys version: 0.6.0 */
 /* bindgen clang version: clang version 15.0.7 */
 /* clang-rs version: clang version 15.0.7 */
 /* r version: 4.2.3 */
```
full diff: https://github.com/extendr/libR-sys/compare/v0.5.0...v0.6.0

**Comment by yutannihilation** [comment]
It seems I cannot reproduce this with my local R 4.2.2.

**Comment by Ilia-Kosenkov** [comment]
Can we just re-run it here? Sometimes it is something flaky in builds/runner setup

**Comment by yutannihilation** [comment]
I already tried.

1st run: https://github.com/extendr/extendr/actions/runs/5572135550/jobs/10177843937
2nd run: https://github.com/extendr/extendr/actions/runs/5572135550/jobs/10178386289

**Comment by Ilia-Kosenkov** [comment]
I just noticed that it is actually rextendr misbehaving. I will try to check it when I have time

**Comment by yutannihilation** [comment]
Thanks. Yes, this is about rextendr. I forgot to mention here, but I confirmed rextendr's CI also fails. So, something should have happened after the last commit of rextendr.

https://github.com/extendr/rextendr/pull/301

**Comment by Ilia-Kosenkov** [comment]
Oh no, I know what it is -- path to ndarray library is `260` symbols long. It is an ancient Widows path limitation issue, which is why it is not reproduced locally

**Comment by yutannihilation** [comment]
Oh..., so, should we disable the tests? I'm not sure why it worked before 2 weeks ago, though.

**Comment by Ilia-Kosenkov** [comment]
A good question, right now I am not 100% sure. I wonder if we can temporarily reduce the path length.

Why it misbehaves - also not sure. New version of cargo with different paths?

**Comment by yutannihilation** [comment]
> New version of cargo with different paths?

Ah, I don't know about the details of the update in 1.71, but it might matter. Let's try with 1.70.

**Comment by yutannihilation** [comment]
Confirmed. I ran the CI with Rust 1.70 and 1.71, and it seems 1.70 passes, while 1.71 fails.

https://github.com/extendr/rextendr/actions/runs/5574728108/jobs/10183703676?pr=302

I guess the difference between R 4.2 and R 4.3 (more specifically, Rtools 42 and Rtools 43) is the long path support.

https://blog.r-project.org/2023/03/07/path-length-limit-on-windows/

**Review by Ilia-Kosenkov — APPROVED** [review]

**Pull request merged**
