### PR TITLE
Tweak on doc of `eventHelper()`

### PR DESCRIPTION
**Pull request by yutannihilation**
A small followup of #389

### CODE REVIEW

**Comment by yutannihilation** [comment]
No, I just wanted to prevent these words from appearing in the doc as this doesn't look very helpful to users. Thanks for approving.

image

**Comment by multimeric** [comment]
Ah right you changed it from `///` to `//`. Still looks fine!

**Comment by multimeric** [comment]
Actually while you're thinking about that function, do you think you could rename it to `snake_case` ie `event_helper`? It should have been caught in code review for #389.

**Comment by yutannihilation** [comment]
Ah, it seems so. Sorry, that was my fault. Probably I can fix it next week or so.

**Pull request merged**
