### PR TITLE
Various documentation updates

### PR DESCRIPTION
**Pull request by CGMossa**
These are plucked from the fork I've been toying with. I'm open to changes, but mostly I want move this along

### CODE REVIEW

**Review by JosiahParry — DISMISSED** [review]
thank you!

**Comment by JosiahParry** [comment]
There is a cargo fmt issue with Ubuntu. If you can update that I think this is ready to be merged. There is clearly an issue with rtools on windows that is unrelated to this PR and #747

**Comment by yutannihilation** [comment]
Probably you simply need to slide `rtools-version`?

https://github.com/extendr/extendr/blob/002ec3f55ab9ae4b69762ffac9e8c36212068042/.github/workflows/test.yml#L29-L31

**Comment by CGMossa** [comment]
Brilliant! This was happening on libR-sys, so I did something _there_ and forgot about it here!

**Review by JosiahParry — APPROVED** [review]
Existing CI is out of our hands and is caused by stringi. Merging! Thank you!!

**Pull request merged**
