### PR TITLE
Add invisible() to calls that return nothing.

### LINKED ISSUE #148: More infrastructure needed for wrapper code
The following features are still missing from the metadata code, I believe:

1. Ability to determine whether an extendr function has a return value or not. Functions without return value need to return `invisible()`.
2. Ability to determine the name of the extendr module by calling a generic function (e.g., `wrap__get_module_name`). This is needed for rextendr.

### PR DESCRIPTION
**Pull request by clauswilke**
Closes #148.

### CODE REVIEW

**Review by Ilia-Kosenkov — APPROVED** [review]
I confirm this PR solves incorrect wrapper generation for the new test added in #149.
UPD: it seems you forgot to format Rust code, formatting test is failing.

**Comment by andy-thomason** [comment]
You may be able to add a git hook to run "cargo fmt" as a pre-commit step.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by clauswilke** [comment]
Thanks! I have this irrational preference for doing things manually, but I should at least run `cargo fmt` before committing. :-)

**Comment by andy-thomason** [comment]
Just add a file with

```
#!/bin/sh

cargo fmt
```

to
`.git/hooks/pre-commit`

and

```
chmod 755 .git/hooks/pre-commit 
```

**Pull request merged**
