### PR TITLE
Rename Character to Char

### PR DESCRIPTION
**Pull request by andy-thomason**
This PR is a prelude to introducing a Character wrapper around
string vectors.

The existing Character wrapper referred to CHARSXP instead
of STRSXP.

### CODE REVIEW

**Comment by clauswilke** [comment]
We should probably conclude the discussion in #261 first, so we rename only once.

@Ilia-Kosenkov Could you update the naming in #261 to the latest state of the discussion? Specifically use of plural instead of singular?

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
Could you please summarize all the required naming changes in #261 before I modify the doc?
I am afraid I might've missed some relevant discussions in other PRs/issues.

**Comment by clauswilke** [comment]
I believe we discussed using `Strings` for `CHARSXP`, based on the arguments that (i) collections should be plural words, and (ii) `Characters` is misleading.

**Comment by clauswilke** [comment]
To elaborate:

The argument for plurals was made here: #266 

The argument for `Strings` over `Characters` was made here: https://github.com/extendr/extendr/issues/266#issuecomment-903327040

**Comment by clauswilke** [comment]
@Ilia-Kosenkov Only seeing your comment now. I think this comment summarizes it all: https://github.com/extendr/extendr/issues/266#issuecomment-903327040

**Comment by andy-thomason** [comment]
This PR is completely optional.

The document should be the source of truth.

For example coerce.c has this list of type names:

```
    { "logical",	LGLSXP,	   TRUE },
    { "integer",	INTSXP,	   TRUE },
    { "double",		REALSXP,   TRUE },
    { "raw",		RAWSXP,    TRUE },
    { "complex",	CPLXSXP,   TRUE },
    { "character",	STRSXP,	   TRUE },
    { "expression",	EXPRSXP,   TRUE },
    { "list",		VECSXP,	   TRUE },
    { "environment",    ENVSXP,    FALSE },
    { "char",		CHARSXP,   TRUE },
    { "externalptr",	EXTPTRSXP,  FALSE },
    { "weakref",	WEAKREFSXP, FALSE },
    { "name",		SYMSXP,	   FALSE },
```

**Comment by clauswilke** [comment]
I see. I think I've been confusing `CHARSXP` and `STRSXP`. Is this correct:

- `CHARSXP`: A single string, i.e., a vector of individual characters using the conventional understanding of the word "character"
- `STRSXP`: A vector of `CHARSXP`s, i.e., a vector of strings

If this is correct, then we should probably use `Rstr` instead of `Char`, to remain consistent with the naming scheme that R internal scalar types are named Rtype.

**Comment by Ilia-Kosenkov** [comment]
This somewhat explains it:
``` r
.Internal(inspect(letters))         
#> @0x00000000144636d8 16 STRSXP g0c7 [REF(1)] (len=26, tl=0)
#>   @0x0000000012e19e38 09 CHARSXP g0c1 [MARK,REF(26),gp=0x61] [ASCII] [cached] "a"
#>   @0x00000000131f26f0 09 CHARSXP g0c1 [MARK,REF(10),gp=0x61] [ASCII] [cached] "b"
#>   @0x00000000044729f0 09 CHARSXP g0c1 [MARK,REF(292),gp=0x61] [ASCII] [cached] "c"
#>   @0x00000000130117a8 09 CHARSXP g0c1 [MARK,REF(3),gp=0x61] [ASCII] [cached] "d"
#>   @0x00000000044b3188 09 CHARSXP g0c1 [MARK,REF(3),gp=0x61] [ASCII] [cached] "e"
#>   ...
```

<sup>Created on 2021-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
@andy-thomason Why not just do a search and replace of `Char` with `Rstr` and then merge this PR?

**Pull request closed without merging**
