### PR TITLE
Revert "Minor warning clean-up"

### PR DESCRIPTION
**Pull request by CGMossa**
Reverts extendr/extendr#512

### CODE REVIEW

**Comment by CGMossa** [comment]
I merged a PR that passed CI completely in the PR, but on the branch once merged that is, it no longer passes it. I may know why, but now I need to revert what was merged.

**Comment by multimeric** [comment]
I can't parse that sentence, but anyway if you can find an easy fix I don't mind if we skip the reversion and go straight for the fix.

**Comment by CGMossa** [comment]
I don't understand what is wrong here. I don't understand why reverting the PR doesn't pass CI. I'm completely lost now.

**Comment by yutannihilation** [comment]
I think this setup is wrong. `Sys.setenv()` is effective on the same session, so this doesn't work on the next step.

https://github.com/extendr/extendr/blob/b5a5350541cd2d219a8732a017732e052bc1cc1a/.github/workflows/test.yml#L257-L274

**Comment by yutannihilation** [comment]
Confirmed. 

https://github.com/extendr/extendr/pull/517

**Comment by CGMossa** [comment]
Since @yutannihilation fixef this in #515, closing this.

I don't know if we should be testing with rextendr either.

**Pull request closed without merging**
