### PR TITLE
Update syn crate to version 2

### PR DESCRIPTION
**Pull request by yutannihilation**
Disclaimer: I don't intend to merge this because it would conflicts with several ongoing pull requests. The main purpose of this is is to show how updating is possible, and (the second purpose is to train myself).

As discussed in https://github.com/extendr/extendr/pull/574, extendr seems to have some motivation to update the syn crate. Here's some code and references:

* [Release note of Syn 2.0](https://github.com/dtolnay/syn/releases/tag/2.0.0)
* [`syn::parse`](https://docs.rs/syn/latest/syn/parse/index.html)
* [`syn::meta::parser`](https://docs.rs/syn/latest/syn/meta/fn.parser.html)
* [`syn::Attribute`](https://docs.rs/syn/latest/syn/struct.Attribute.html)
* [When to choose `Attribute::parse_nested_meta` or `syn::meta::parser`](https://docs.rs/syn/latest/syn/meta/struct.ParseNestedMeta.html#examples)

Sorry for no explanations about the changes. I might write some in future if I get some time.

### CODE REVIEW

**Comment by eitsupi** [comment]
Currently prqlr includes two versions of syn.
https://github.com/cran/prqlr/blob/9b1cb4c827eaf303d5bbbe74df7ec5e5fb320d7d/LICENSE.note#L556-L572

It would be great if this PR is merged.

**Comment by CGMossa** [comment]
I have looked at this PR, and looked at doing the upgrade myself, but when I did it, I faced so many more issues. Maybe I choose the wrong way to upgrade the code.
This looks very succinct.

**Comment by CGMossa** [comment]
Dear @yutannihilation, I like this and I think we should merge this.

The PRs that are currently up are mostly abandoned (due to inaction from our side), or otherwise
will need attention. I think a good path is to work on the PRs, that we all understand, and value, and then
we can unblock our attention and focus on those larger PRs.

Upgrading syn now is better. 

Let me know how I can assist here.

**Comment by yutannihilation** [comment]
Sure. I think this should work.

**Review by CGMossa — APPROVED** [review]
LGTM

**Pull request merged**
