### PR TITLE
Remove MSYS2 path on GitHub Actions CI

### PR DESCRIPTION
**Pull request by yutannihilation**
As https://github.com/extendr/rextendr/issues/91 did commited on rextendr, probably we can do the same thing on extendr as well?

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation, you cannot throw away `mingw` dependency completely. You may try to replace `msys2` with Rtools on the `PATH`, but I am not 100% sure all extendr tests can be executed without `msys2`.

Right now the CI fails because there are no `mingw` compilers on the path.

**Comment by yutannihilation** [comment]
I see, thanks. Apparently, we cannot go away from msys2 on w/ bindgen cases...

**Comment by Ilia-Kosenkov** [comment]
I checked locally, it seems that almost all tests rely on bindgen (except for `test-minimal` subset and perhaps some other), and bindgen requires clang, which is not provided by Rtools. The only solution is to use `msys2` for this pruposes.

**Comment by yutannihilation** [comment]
Hmm, okay, I optimistically thought `tests_no_bindgen` cases are without bindgen, as the name suggests... Sorry for taking your time. I give up here.

**Pull request closed without merging**
