### PR TITLE
Int, Real conversions follow-up

### PR DESCRIPTION
**Pull request by brendanrbrown**
A requested follow-up to #258.

Maintainers should feel free to mark this PR as draft (or I can) if deemed more appropriate: 

The implementation is very likely to change once the discussion in #261, #251 solidifies. In particular, wrapping types such as `Rint` if implemented would be used here. Better NA handling and error types in `TryFrom<Robj> for Int/Real` would also follow, which I think is needed.

### CODE REVIEW

**Comment by clauswilke** [comment]
Thanks! I think this PR highlights that types such as `Rint` are needed and should probably be implemented first. (Or you could do so as part of this PR.) There's no good reason to duplicate conversion code in multiple places, as we would be doing right now. I'll open a separate issue on this topic and link here.

**Comment by clauswilke** [comment]
I have filed issues #265 and #266 that cover relevant discussions we should have before proceeding. I think we need at least consensus on #265 before we can finalize this PR.

**Comment by brendanrbrown** [comment]
> I think we need at least consensus on #265 before we can finalize this PR.

Entirely agree, and as you suggest this PR is meant in part to point out some cases in which these changes are needed. Thanks for filing these issues and for marking this PR as draft.

**Comment by brendanrbrown** [comment]
It looks to me as though this PR can be closed, in light of #284 and #274, which seem to fill the holes discussed above. If others agree I (or they) can close it.

This does leave open the question of what to do with the remaining `Real` and `Int` types -- but that is for a separate issue or PR I think.

**Comment by clauswilke** [comment]
Yes, agreed. Please file issues for any items that you can think of that should be addressed. Thanks!

**Pull request closed without merging**
