### PR TITLE
package_name_to_exported_wrapper

### PR DESCRIPTION
**Pull request by CGMossa**

### CODE REVIEW

**Comment by CGMossa** [comment]
This is untested on macos/linux. 
It works on Windows. 

I hope either a that I can pull in some CI testing, or something tests this with rextendr on those platforms.

**Comment by clauswilke** [comment]
This won't work. See here: https://github.com/extendr/extendr/issues/123#issuecomment-760383469

**Comment by CGMossa** [comment]
I've thought about it, and now see what the problem is: The wrapper in R should be agnostic to whether the platform used was
windows, linux or mac. 

I would like to still suggest that that code is still part of the exported wrapper code, as the crate-name is the same, and 
one only needs to detect what platform the current R instance is on. That code can be amended to the wrapper exporter code in Rust.

I'll do that here as to experiment with it.

**Comment by clauswilke** [comment]
Honestly, this is not that useful. If you want to work on this part of the code, it would be more helpful to add a code path that outputs the info required to reconstruct wrappers into a csv file. (Function names, argument names, return/no return, docstrings if available.)

**Comment by andy-thomason** [comment]
I would welcome you to take a look at the metadata branch. This may make R code generation a lot easier.

**Comment by clauswilke** [comment]
Yes, but see: https://github.com/extendr/extendr/pull/128#issuecomment-761631432

I think we'll still have to generate output during the macro expansion phase. Otherwise we're back to regular expressions.

**Comment by andy-thomason** [comment]
I've taken this on board for the metadata wrapper builder.

I may remove the old wrapper generator as it has been subsumed into the metadata variety.

Would you mind if I closed this PR?

**Comment by clauswilke** [comment]
The old wrapper generator is still being used by rextendr, though. Please don't remove it until we have ported rextendr. Relevant issue: https://github.com/extendr/rextendr/issues/28

**Comment by clauswilke** [comment]
But yes, this PR can be closed I think.

**Comment by andy-thomason** [comment]
Closing as this been incorporated in the metadata.

**Pull request closed without merging**
